### ISSUE TITLE
Google Voice no longer working

### ISSUE THREAD

**Issue by naftulikay** [The-MAZZTer/One-Number#3]
It seems that recently, Google made a change that breaks Google Voice integration with One Number. No matter what I do, I'm still seeing this:

![hello](http://www.picamatic.com/show/2012/04/07/12/16/8332741_567x189.png)

Can you please update One Number to work with Google Voice again?

**Comment by navarr** [comment]
I do not encounter this issue. (I'm also not the dev but, thats my two pence)

**Comment by The-MAZZTer** [comment]
You probably just need to visit the site so it updates your cookies, then it should refresh correctly.  I don't think there's a way around that.

Trust me if it broke I'd notice almost immediately (and would try to fix it) since I use One Number myself. :)

**Comment by The-MAZZTer** [comment]
I AM NOT GOOD AT GITHUB hmm
