### ISSUE TITLE
Jeez, can u make this more complex?

### ISSUE THREAD

**Issue by kcstarr** [The-MAZZTer/One-Number#8]
Hate 2 b snarky...but...I followed barely decipherable instructions in ur 'Readme' post. I got, "Error Loading Extension" & the following, 
"Failed to load extension from: ~/Downloads/src
Manifest file is missing or unreadable.
Could not load manifest." 
I'm over 65, getting a divorce after 40 yrs because my partner is violent & delusional related to dementia &, in spite of large Rx opioids still suffering from chronic pain. I'm grumpy...granted. But really, I'm not a developer & still recovering from years of Windows (now enjoying the much simpler Chrome OS). How on earth am I supposed to follow the (to me @least) less than simple directions here @ GitHub?

**Comment by The-MAZZTer** [comment]
The easiest way to install is from the Chrome Web Store: https://chrome.google.com/webstore/detail/one-number/cfkohgkpafhkpdcnfadadcibfboapggi

You can use Chrome's built in tools if you are interested in looking at the source code. You only need to follow the instructions provided if you are interested in modifying the project. If that is the case, I would suggest you verify the files are all extracted into the proper location. The error you are getting occurs if the folder you select to load does not include the manifest.json. The files probably got extracted somewhere else by accident.

GitHub provides a tool called "GitHub Desktop" which provides a GUI interface and makes it simple to pull down and manage GIT repositories from GitHub. I would recommend it if you're interested in pulling down projects to your local PC. https://desktop.github.com/

Unfortunately three out of the four services One Number supported no longer function. I would recommend for the remainder (Gmail) if you are interested in a browser extension you may want to look elsewhere... One Number is a bit dated. I actually do not use it myself any more.

I have lots of ideas and plans to revitalize One Number and make it far more useful than it ever was before, but sadly coding for a living saps most of my motivation for personal projects. One day I'll get back to it though.

**Comment by kcstarr** [comment]
thx 4 ur response; however, I shud hve told u that I'm on a Chromebook, which, therefore, limits me to Chrome OS. As a result the link u provided for the desktop github project is moot. I understand u r quite busy - but is there no way to take the now limited app off the Chrome Web Store? Might belay other people having problems. No need to respond; I'm most appreciative for ur time in responding. John
